In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler 
from sklearn.ensemble import RandomForestRegressor
df = pd.read_csv(r"E:\projects\regression\airbnb_top_cities.csv")

C:\Users\jishn\AppData\Local\Temp\ipykernel_5644\2540295413.py:8: DtypeWarning: Columns (4,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"E:\projects\regression\airbnb_top_cities.csv")

In [3]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,city,scrape_date
0,13913,Holiday London DB Room Let-on going,54730,Alina,NaN,Islington,51.56861,-0.11270,Private room,70.0,1,55,2025-08-21,0.30,2,331,10,NaN,London,2026-03-29
1,15400,Bright Chelsea Apartment. Chelsea!,60302,Philippa,NaN,Kensington and Chelsea,51.48780,-0.16813,Entire home/apt,149.0,4,97,2025-04-05,0.51,1,199,1,NaN,London,2026-03-29
2,17402,Very Central Modern 3-Bed/2 Bath By Oxford St W1,67564,Liz,NaN,Westminster,51.52195,-0.14094,Entire home/apt,411.0,3,56,2024-02-19,0.32,2,80,0,NaN,London,2026-03-29
3,24328,Battersea live/work artist house,41759,Joe,NaN,Wandsworth,51.47072,-0.16266,Entire home/apt,NaN,7,95,2025-07-05,0.53,1,294,1,NaN,London,2026-03-29
4,36274,Bright 1 bedroom apt off brick lane in Shoreditch,133271,Hendryks,NaN,Tower Hamlets,51.52322,-0.06979,Entire home/apt,210.0,5,15,2025-09-06,0.09,2,323,6,NaN,London,2026-03-29

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 292802 entries, 0 to 292801
Data columns (total 20 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              292802 non-null  int64
 1   name                            292802 non-null  object
 2   host_id                         292802 non-null  int64
 3   host_name                       292712 non-null  object
 4   neighbourhood_group             19410 non-null   object
 5   neighbourhood                   292802 non-null  object
 6   latitude                        292802 non-null  float64
 7   longitude                       292802 non-null  float64
 8   room_type                       292802 non-null  object
 9   price                           139950 non-null  float64
 10  minimum_nights                  292802 non-null  int64
 11  number_of_reviews               292802 non-null  int64
 12  last_review                     226437 non-null  object
 13  reviews_per_month               226437 non-null  float64
 14  calculated_host_listings_count  292802 non-null  int64
 15  availability_365                292802 non-null  int64
 16  number_of_reviews_ltm           292802 non-null  int64
 17  license                         139853 non-null  object
 18  city                            292802 non-null  object
 19  scrape_date                     292802 non-null  object
dtypes: float64(4), int64(7), object(9)
memory usage: 44.7+ MB

In [5]:
#dropping useless columns
df = df.drop(['id', 'name', 'host_id', 'host_name',
              'last_review', 'license', 'scrape_date','neighbourhood_group'], axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 292802 entries, 0 to 292801
Data columns (total 12 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   neighbourhood                   292802 non-null  object
 1   latitude                        292802 non-null  float64
 2   longitude                       292802 non-null  float64
 3   room_type                       292802 non-null  object
 4   price                           139950 non-null  float64
 5   minimum_nights                  292802 non-null  int64
 6   number_of_reviews               292802 non-null  int64
 7   reviews_per_month               226437 non-null  float64
 8   calculated_host_listings_count  292802 non-null  int64
 9   availability_365                292802 non-null  int64
 10  number_of_reviews_ltm           292802 non-null  int64
 11  city                            292802 non-null  object
dtypes: float64(4), int64(5), object(3)
memory usage: 26.8+ MB

In [6]:
#dropping rows with missing price values
df = df.dropna(subset = ['price'])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 139950 entries, 0 to 275071
Data columns (total 12 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   neighbourhood                   139950 non-null  object
 1   latitude                        139950 non-null  float64
 2   longitude                       139950 non-null  float64
 3   room_type                       139950 non-null  object
 4   price                           139950 non-null  float64
 5   minimum_nights                  139950 non-null  int64
 6   number_of_reviews               139950 non-null  int64
 7   reviews_per_month               110447 non-null  float64
 8   calculated_host_listings_count  139950 non-null  int64
 9   availability_365                139950 non-null  int64
 10  number_of_reviews_ltm           139950 non-null  int64
 11  city                            139950 non-null  object
dtypes: float64(4), int64(5), object(3)
memory usage: 13.9+ MB

In [8]:
df['reviews_per_month']= df['reviews_per_month'].fillna(0)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 139950 entries, 0 to 275071
Data columns (total 12 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   neighbourhood                   139950 non-null  object
 1   latitude                        139950 non-null  float64
 2   longitude                       139950 non-null  float64
 3   room_type                       139950 non-null  object
 4   price                           139950 non-null  float64
 5   minimum_nights                  139950 non-null  int64
 6   number_of_reviews               139950 non-null  int64
 7   reviews_per_month               139950 non-null  float64
 8   calculated_host_listings_count  139950 non-null  int64
 9   availability_365                139950 non-null  int64
 10  number_of_reviews_ltm           139950 non-null  int64
 11  city                            139950 non-null  object
dtypes: float64(4), int64(5), object(3)
memory usage: 13.9+ MB

In [9]:
df.head()

,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,city
0,Islington,51.56861,-0.11270,Private room,70.0,1,55,0.30,2,331,10,London
1,Kensington and Chelsea,51.48780,-0.16813,Entire home/apt,149.0,4,97,0.51,1,199,1,London
2,Westminster,51.52195,-0.14094,Entire home/apt,411.0,3,56,0.32,2,80,0,London
4,Tower Hamlets,51.52322,-0.06979,Entire home/apt,210.0,5,15,0.09,2,323,6,London
5,Richmond upon Thames,51.48145,-0.28107,Entire home/apt,280.0,3,116,0.64,1,324,6,London

In [10]:
#keeping data with possible prices
df = df[(df['price']>20) & (df['price']<1500)]
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 128644 entries, 0 to 275071
Data columns (total 12 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   neighbourhood                   128644 non-null  object
 1   latitude                        128644 non-null  float64
 2   longitude                       128644 non-null  float64
 3   room_type                       128644 non-null  object
 4   price                           128644 non-null  float64
 5   minimum_nights                  128644 non-null  int64
 6   number_of_reviews               128644 non-null  int64
 7   reviews_per_month               128644 non-null  float64
 8   calculated_host_listings_count  128644 non-null  int64
 9   availability_365                128644 non-null  int64
 10  number_of_reviews_ltm           128644 non-null  int64
 11  city                            128644 non-null  object
dtypes: float64(4), int64(5), object(3)
memory usage: 12.8+ MB

In [11]:
cat_col = ['city', 'room_type', 'neighbourhood']
for col in cat_col:
    if col in df.columns:
        df = pd.get_dummies(df, columns = [col], drop_first=True)
df.head()

,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,city_Bangkok,...,neighbourhood_la Teixonera,neighbourhood_la Trinitat Nova,neighbourhood_la Trinitat Vella,neighbourhood_la Vall d'Hebron,neighbourhood_la Verneda i la Pau,neighbourhood_la Vila Olímpica del Poblenou,neighbourhood_la Vila de Gràcia,neighbourhood_les Corts,neighbourhood_les Roquetes,neighbourhood_les Tres Torres
0,51.56861,-0.11270,70.0,1,55,0.30,2,331,10,False,...,False,False,False,False,False,False,False,False,False,False
1,51.48780,-0.16813,149.0,4,97,0.51,1,199,1,False,...,False,False,False,False,False,False,False,False,False,False
2,51.52195,-0.14094,411.0,3,56,0.32,2,80,0,False,...,False,False,False,False,False,False,False,False,False,False
4,51.52322,-0.06979,210.0,5,15,0.09,2,323,6,False,...,False,False,False,False,False,False,False,False,False,False
5,51.48145,-0.28107,280.0,3,116,0.64,1,324,6,False,...,False,False,False,False,False,False,False,False,False,False

In [12]:
#splitting the dataset for training and testing
x = df.drop('price',axis=1)
y = df['price']
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=42)

In [13]:
#feature scaling using StandardScaler
scaler=StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [14]:
#Linear Regression
lr_model = LinearRegression()
lr_model.fit(x_train_scaled, y_train)

lr_pred = lr_model.predict(x_test_scaled)

print("Linear Regression Results:")
print("MSE:", mean_squared_error(y_test, lr_pred))
print("R2 Score:", r2_score(y_test, lr_pred))

Linear Regression Results:
MSE: 24429.753442431447
R2 Score: 0.7223799703867541

In [18]:
#Random Forest Regressor
model = RandomForestRegressor(
    n_estimators=300,
    max_depth=None,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features='sqrt',
    random_state=42,
    n_jobs=-1
)
model.fit(x_train_scaled,y_train)

rf_pred = model.predict(x_test_scaled)

print("\nRandom Forest Results:")
print("MSE:", mean_squared_error(y_test, rf_pred))
print("R2 Score:", r2_score(y_test, rf_pred))

Random Forest Results:
MSE: 18637.75175398756
R2 Score: 0.7882003514255945

In [16]:
from sklearn.ensemble import GradientBoostingRegressor 
gb_model = GradientBoostingRegressor(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=5,
    random_state=42
)

gb_model.fit(x_train, y_train)
gb_pred = gb_model.predict(x_test)

In [17]:
print("Gradient Boosting Results:")
print("MSE:", mean_squared_error(y_test, gb_pred))
print("R2 Score:", r2_score(y_test, gb_pred))

Gradient Boosting Results:
MSE: 19952.29388566743
R2 Score: 0.7732618778800137

In [ ]:
Q1 = data['price'].quantile(0.25)
Q3 = data['price'].quantile(0.75)
IQR = Q3 - Q1

data = data[(data['price'] >= Q1 - 1.5*IQR) & 
            (data['price'] <= Q3 + 1.5*IQR)]